TGSAI/segy

tests/conftest.py, tests/schema/conftest.py, tests/schema/test_data_type.py, tests/schema/test_header.py, tests/schema/test_segy_descriptor.py
The tests added in this PR include checks for expected exceptions of components defined under schema, and creating a custom SegyDescriptor object.
=> Populate remaining tests for schemas.

noxfile.py
Hey @tasansal - looks to me like its this jupyter notebook thats causing the infinite loop for sphinx-autobuild. Let me know if this works for you!
=> Fix sphinx-autobuild infinite loop bug

README.md
Include links to the Conda-Forge and Conda documentation in the README to provide users with additional resources for package installation and management.
=> Add Conda links to README

src/segy/cli/common.py, src/segy/schema/__init__.py, src/segy/schema/base.py, src/segy/schema/trace.py, src/segy/standards/__init__.py, src/segy/standards/registry.py, tests/conftest.py, tests/main/test_ibm_ieee.py, tests/main/test_indexing.py, tests/schema/test_data_type.py, tests/schema/test_header.py, tests/schema/test_segy_descriptor.py, tests/standards/test_registry.py
Several files have been updated to improve their readability by adjusting the whitespace. This includes mostly adding an empty line after the initial comment line, or removing an unnecessary empty line. The changes have been applied both to source and test files.
=> Adjust module doctoring whitespaces

src/segy/file.py, tests/test_transforms.py
Added a check for fields that are of type Ibm32 in the HeaderIndexer. Included another case in test for test_transforms.py.
=> Support for handling IBM float trace headers

poetry.lock, pyproject.toml
The project's dependencies have been updated. The version of "numba" was upgraded from 0.59.0 to 0.59.1, and "typer" from 0.11.1 to 0.12.0. Additionally, the version of "ruff" in dev dependencies was bumped from 0.3.4 to 0.3.5. "click-params" was removed from the list of dependencies.
=> Update `typer` and `numba` to latest.

.github/workflows/tests.yaml
CI was breaking with the latest runners, so changed to absolute paths.
=> Fix broken CI: Make CI tooling constraint paths absolute

src/segy/arrays.py, tests/test_arrays.py
A `copy` method, which maintains raw binary data and padding bytes, has been added to the `SegyArray`. This is essential for SEG-Y data processing where unparsed fields are present and preserving raw (uninterpreted) binary data integrity is crucial.
=> Override Numpy's copy method to `SegyArray` to ensure uninterpreted bytes are preserved.

src/segy/file.py, src/segy/indexing.py
For memory efficiency, we are going to make transforms apply in-place. This would require the underlying memory to be mutable. The original `bytes` are immutable, so we convert them to `bytearray` on the spot.
=> Make fetched raw bytes mutable for downstream transforms

src/segy/transforms.py, tests/test_transforms.py
Made byte-swapping in-place. IBM to IEEE is already in place. Not sure about IEEE to IBM, will check that if it becomes a problem.
Removed the scaling and casting transforms because we don't need them anymore. This also allowed us to simplify the dtype casting logic for transforms since the data type itemsize isn't expected to change anymore.
=> Make transforms in-place and remove unnecessary transforms to simplify logic

src/segy/cli/dump.py, src/segy/factory.py, src/segy/file.py, src/segy/schema/segy.py, src/segy/standards/__init__.py, src/segy/standards/minimal.py, src/segy/standards/registry.py, tests/test_schema_segy.py, tests/test_segy_factory.py, tests/test_segy_file.py, tests/test_standards_registry.py
The SEG-Y standard registration method and retrieval method have been renamed for clarity. Now, they are called `register_segy_standard` and `get_segy_standard`. Also, the `SegyStandard` property for `SegyDescriptor` and all its references is updated which can be `None`. This change helps with custom schemas and makes the numbering more strict. 
We only allow `{0.0, 1.0, 2.0, 2.1, None}` as values now.
=> Refactor SEG-Y standard registration and retrieval and make it more strict

src/segy/standards/rev0.py, src/segy/standards/rev1.py
The field names in trace header fields for SEGY standards rev 0 and 1 have been revised. In revision 1, "x_coordinate" has been changed to "cdp_x", "y_coordinate" to "cdp_y", etc. For revision 0, "cdp_ens_no" is now "ensemble_no" and "vert_sum" is updated to "vertical_sum". These changes aim to enhance consistency with standards.
=> Update canonical SEG-Y header field names in SEGY standards revisions 0 and 1

src/segy/accessors.py, src/segy/file.py, src/segy/transforms.py, tests/test_accessors.py
This PR is to move the logic for creating decoding transforms for SegyArrays accessors out of the SegyFile class. This way they are not recreated every time the accessors are used for a SegyFile instance.
=> Decoupled transformation logic from `SegyFile`

src/segy/schema/data_type.py, tests/test_schema_data_type.py, tests/test_segy_factory.py
Added checks for duplicate fields and offset limits in StructuredDataTypeDescriptor. Also provided functions to add or remove fields, thereby enhancing management of field elements. These improvements ensure that fields are unique and do not exceed allowed item size, simplifying the process of adding or removing fields.
=> Improve field management for `StructuredDataTypeDescriptor` (add/remove)

README.md, docs/api_reference.md, docs/cli_usage.md, docs/data_models/data_type.md, docs/data_models/file.md, docs/settings.md, docs/tutorials/creation.ipynb, docs/tutorials/quickstart.ipynb, poetry.lock, src/segy/config.py, src/segy/factory.py, src/segy/file.py, src/segy/schema/segy.py, src/segy/schema/text_header.py, src/segy/standards/__init__.py, src/segy/standards/registry.py, tests/test_segy_file.py, tests/test_standards_registry.py
=> Simplify SEG-Y parsing settings and documentation cleanup

src/segy/factory.py, tests/test_segy_factory.py
The `create_binary_header` function in factory now accepts an optional `update` parameter. This dictionary contains binary header fields that need to be modified from default. The function will update these fields with the values specified in the update dictionary before returning the encoded binary header.
=> Allow updating binary header fields in SEG-Y factory.

src/segy/alias/segyio.py
The `SourceEnergyDirectionExponent` field was incorrectly mapped to `trace.Rev1.SOURCE_ENERGY_DIR_MANTISSA`. This PR fixes that.
=> Fix typo in segyio -> segy aliases

src/segy/arrays.py
The logical error in the check within the `__getitem__` and `__setitem__` methods of `src/segy/arrays.py` has been rectified. The previous condition did not ensure that the items or keys passed were in `HeaderArray.dtype.names`.
=> Fix logical error in array item checks

src/segy/config.py, src/segy/file.py, src/segy/indexing.py, tests/test_segy_file.py
The endianness inference in edge cases or overrides were clunky. Now made it more streamlined and automated.
=> Streamline endianness inference

poetry.lock, src/segy/accessors.py, src/segy/transforms.py, tests/test_accessors.py
Resolves #168 
The TraceAccessor was constructing the wrong pipeline when IBM-float header keys were present. It was not decoding the IBM-float headers. The `SegyFile`'s `.trace` method was returning wrong values. However, the `.header` accessor works fine because the pipeline is correct.
The fundamental issue is: `Transform` and `TransformPipeline` has no way to apply nested decoding transformations. As a workaround (without changing the fundamental design), I implemented a `TraceTransform`, which applies a trace's header and data transforms pipelines in sequence. This is terrible because it introduces a circular dependency: `TransformPipeline` depends on `Transform`s, which depends on `TransformPipeline`s. You can also see all the typing issues we had to ignore.
This was a quick fix, …
=> Fix bug in decoding IBM-float values in trace accessor

src/segy/indexing.py, tests/test_indexing.py, tests/test_segy_file.py
**tl;dr**
* Return traces/headers etc., in user-requested order.
* Allow ndarray indexing
* Consolidate int, ndarray, and list indexing to a single function
If users asked for traces in descending or random order, the read optimizations returned traces/headers in an unexpectedly sorted order. We now return in the same order the user asked for.
=> Improve data getter functionality

src/segy/constants.py, src/segy/factory.py, src/segy/file.py, src/segy/transforms.py, tests/test_segy_factory.py, tests/test_transforms.py
Introduced a new `SegyRevisionTransform` class to interpret the SEG-Y revision field in the binary header. This transform has been added to the `transform_map` and applied in the SEG-Y file processing pipeline. The code raises a `NotImplementedError` for SEG-Y revisions 2 and above.
=> Interpret SEG-Y revision in binary header

src/segy/schema/format.py
Previously, the method did not account for string length. This change includes a condition to directly return string types without conversion. Additionally, comments were added for clarity on different data type sections.
=> Fix incorrect variable length string data type creation

poetry.lock, pyproject.toml
Relax Numba version constraints to allow versions >=0.59.1 and <0.70.0. This change ensures compatibility with older numba.
Also formatted the `pyproject.toml` with `prettier`.
=> Relax Numba version constraints

pyproject.toml, src/segy/accessors.py, src/segy/exceptions.py, src/segy/factory.py, src/segy/file.py, src/segy/indexing.py, src/segy/standards/registry.py, src/segy/transforms.py, tests/test_segy_file.py
Added logging and better exception handling for `SegyFile` overall.
Also improved test coverage with extended text header inference and override (while adding logging).
=> Implement logging for SegyFile

.github/workflows/labeler.yaml
Reverts TGSAI/segy#205. It broke CI.
=> Revert "Bump crazy-max/ghaction-github-labeler from 5.0.0 to 5.1.0"

src/segy/factory.py
It wasn't being written, now it is.
=> Add endianness indicator code when creating Rev2+ SEG-Y files

README.md, src/segy/standards/__init__.py, src/segy/standards/fields/binary.py, src/segy/standards/spec.py, tests/test_segy_file.py
Added modified binary header fields and registered as supported codec.
Fixed incorrect Rev2 fields for ext trace headers + survey type.
Updated tests.
=> Add SEG-Y Revision 2.1 to supported formats

docs/tutorials/quickstart.ipynb, src/segy/indexing.py, tests/test_segy_file.py
If we requested duplicate indices in traces (e.g., ` [0, 1, 2, 3, 1]`), the I/O layer would not fetch them twice but drop them. When re-sorting to the original order, we were missing values, causing an error.
Now, it is ensured that duplicates are found and reconstructed while throwing a warning.
=> Fix indexing issues when duplicate indices are present.

src/segy/alias/segyio.py, src/segy/file.py, src/segy/inference.py, src/segy/transforms.py, tests/test_segy_file.py, tests/test_transforms.py
The SEG-Y revision interpretation for binary header values is improved.
Now it will parse and normalize the header fields in binary header. Previously we left it as is and only interpreted when it was Rev1. Now we interpret it regardless of what it is.
Ignored if rev2+ because major and minor are explicitly stated.
=> Improve Revision Transformation

.pre-commit-config.yaml, CONTRIBUTING.md, README.md, noxfile.py, pyproject.toml, uv.lock
We used to have `nox-poetry` which handled this in the background. Same doesn't exist for `uv`. So we added some convenience functions to make sure locked deps get installed during CI/CD sessions.
=> Use locked dependencies in Nox sessions

src/segy/file.py
Python 3.13.0 has a bug where it can't compare singleton numpy arrays in Enum construction. It was fixed in 3.13.1; however, we should still support 3.13.0. 
In this fix we ensure the singleton item is extracted with `.item()` method, consistent with other value extractions in the same function.
This was noticed due to documentation build errors on readthedocs with 3.13.0.
=> Ensure sample format code value gets extracted from Numpy struct

src/segy/arrays.py, src/segy/indexing.py, tests/test_segy_file.py
This:
```python
slice_ = slice(0, n_traces)
idx = file.trace.normalize_and_validate_query(slice_)  # this is 1st component of file.traces.__getitem__
raw_arr = file.trace.fetch(idx, raw=True)  # this is 2nd component of file.traces.__getitem__
raw_arr_view = raw_arr.view(file.spec.trace.dtype)  # view as defined dtype
raw_to_parsed = file.accessors.trace_decode_pipeline.apply(raw_arr_view.copy())  # copy here bc it normally is inplace
```
should now be equal:
```python
file.traces[slice_]
```
The copy on the first example is there for comparing values because normally trace decode pipeline modifies the array in place.
=> Add a flag to request raw bytes in data indexers
